# Generated by Django 3.0.3 on 2021-02-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('caption', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
        ),
    ]
